name: 🎉 CI to Docker Hub 

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Set up Docker Buildx
                id: buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Cache Docker layers
                uses: actions/cache@v3
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-
            -
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}
            -
                name: Get the current pushed tag
                id: vars
                run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
            -
                name: Build and push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    context: ./ 
                    file: ./Dockerfile
                    builder: ${{ steps.buildx.outputs.name }}
                    push: true
                    tags: signedsecurity/web-hacking-toolkit:latest,signedsecurity/web-hacking-toolkit:${{ steps.vars.outputs.tag }}
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache
            -
                name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}